### ISSUE TITLE
I've an issue with npm install syntax and a fresh install of Node.js 

### ISSUE THREAD

**Issue by jocerfranquiz** [DmitrySoshnikov/syntax#141]
I installed the most recent node and npm. I ran `npm install` inside a cloned git repo of syntax and it failed all 14 tests. Bellow is part of the message:

```bash
 FAIL  src/__tests__/code-unit-test.js
  ● Test suite failed to run

    TypeError: /home/***/syntax/src/__tests__/code-unit-test.js: Cannot read properties of null (reading 'bindings')

      at Scope.bindings [as moveBindingTo] (node_modules/@babel/traverse/src/scope/index.ts:1261:13)
      at BlockScoping.updateScopeInfo (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
      at BlockScoping.run (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
      at PluginPass.BlockStatementSwitchStatementProgram (node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
      at call (node_modules/@babel/traverse/src/visitors.ts:250:21)
      at NodePath.call [as _call] (node_modules/@babel/traverse/src/path/context.ts:34:20)
      at NodePath._call [as call] (node_modules/@babel/traverse/src/path/context.ts:19:17)
      at NodePath.call [as visit] (node_modules/@babel/traverse/src/path/context.ts:92:31)
      at TraversalContext.visit [as visitQueue] (node_modules/@babel/traverse/src/context.ts:144:16)
      at TraversalContext.visitQueue [as visitSingle] (node_modules/@babel/traverse/src/context.ts:108:19)
      at TraversalContext.visitSingle [as visit] (node_modules/@babel/traverse/src/context.ts:176:19)
      at visit (node_modules/@babel/traverse/src/traverse-node.ts:34:17)
      at traverse (node_modules/@babel/traverse/src/index.ts:71:15)
      at transformFile (node_modules/@babel/core/src/transformation/index.ts:119:13)
          at transformFile.next (<anonymous>)
      at transformFile (node_modules/@babel/core/src/transformation/index.ts:47:12)
          at run.next (<anonymous>)
      at transform (node_modules/@babel/core/src/transform.ts:29:20)
          at transform.next (<anonymous>)
      at evaluateSync (node_modules/gensync/index.js:251:28)
      at sync (node_modules/gensync/index.js:89:14)
      at fn (node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:97:14)
      at transformSync (node_modules/@babel/core/src/transform.ts:66:52)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:519:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:648:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:700:19)

Test Suites: 14 failed, 14 total
Tests:       0 total
Snapshots:   0 total
Time:        1.226 s
Ran all test suites.
npm ERR! code 1
npm ERR! path /home/***/syntax
npm ERR! command failed
npm ERR! command sh -c npm run build && npm test
```

Run on Ubuntu 22.04.2 LTS, Node v20.2.0, NPM 9.7.1

**Comment by jocerfranquiz** [comment]
Maybe is a dependencies version issue. I don't know enough Node.js to solve it. I just wanted to correct some minor problems in the Python plugin.

**Comment by jocerfranquiz** [comment]
I'm no longer interested in improving the Python plugging.  I changed my mind and I'm using a Python parser called Lark. It uses EBNF too, so the experience is similar and I can continue with the course.

**Comment by DmitrySoshnikov** [comment]
@maelhos thanks, see if we can rid of some Babel's plugins, such as `babel-plugin-transform-object-rest-spread` and maybe something else.  Probably increasing Node/Babel version in the `package.json` would help.

**Comment by DmitrySoshnikov** [comment]
Should be fixed in https://github.com/DmitrySoshnikov/syntax/commit/0ec6737c4d813259171706677b83670c4cf9a9da.
