### ISSUE TITLE
BNF support '.'

### ISSUE THREAD

**Issue by ckanner** [DmitrySoshnikov/syntax#74]
This is my grammar.g
```
/**
 * Generated parser in Rust.
 *
 * ./bin/syntax -g examples/calc-ast.rs.g -m lalr1 -o lib.rs
 *
 * use syntax::Parser;
 *
 * let parser = Parser::new();
 *
 * let ast = parser.parse("2 + 2 * 2");
 */

%lex

%%

\s+         /* skip whitespace */ return "";

\d+         return "NUMBER";

"+"         return "+";
"*"         return "*";
"."         return ".";

"("         return "(";
")"         return ")";

/lex

%left +
%left *

%{

/**
 * Recursive generic `Node` enum structure.
 */
#[derive(Debug)]
pub enum Node {

    Literal(i32),

    Binary {
        op: &'static str,
        left: Box<Node>,
        right: Box<Node>,
    },
}
/**
 * Final result type returned from `parse` method call.
 */
pub type TResult = Node;
/**
 * Hook executed on parse begin.
 */
fn on_parse_begin(_parser: &mut Parser, string: &'static str) {
    println!("Parsing: {:?}", string);
}

/**
 * Hook executed on parse end.
 */
fn on_parse_end(_parser: &mut Parser, result: &TResult) {
    println!("Parsed: {:?}", result);
}

%}

%%

Expr
    : Expr + Expr {

        // Types of used args ($1, $2, ...), and return type:
        |$1: Node; $3: Node| -> Node;

        $$ = Node::Binary {
            op: "+",
            left: Box::new($1),
            right: Box::new($3),
        }
    }

    | Expr . Expr {
        |$1: Node; $3: Node| -> Node;

        $$ = Node::Binary {
            op: ".",
            left: Box::new($1),
            right: Box::new($3),
        }
    }

    | Expr * Expr {

        |$1: Node; $3: Node| -> Node;

        $$ = Node::Binary {
            op: "*",
            left: Box::new($1),
            right: Box::new($3),
        };

        println!("expr *");
    }

    | (Expr) {

        // No need to define argument types, since we don't do any
        // operations here, and just propagate $2 further.
        $$ = $2;
    }
    | NUMBER {
        || -> Node;
        let n = yytext.parse::<i32>().unwrap();
        $$ = Node::Literal(n);
    };
```
Then I generates it by `syntax-cli -g syntax/grammar.g -m LALR1 -o syntax/src/lib.rs`, and some errors occurs:
```
SyntaxError:

    | Expr . Expr {
           ^
Unexpected token: "." at 84:11.
```
How can I fix it?

**Comment by DmitrySoshnikov** [comment]
@ckanner, thanks for reporting. For now you can use a token name like:

```
"+"         return "PLUS";
"*"         return "MULT";
"."         return "DOT";
```

And in the BNF:

```
Expr PLUS Expr
Expr MULT Expr
Expr DOT Expr
```

**Comment by ckanner** [comment]
@DmitrySoshnikov Thx. And how to write
```
%left +
%left *
%left '.'
```

**Comment by DmitrySoshnikov** [comment]
The same:

```
%left PLUS
%left MULT
%left DOT
```

**Comment by ckanner** [comment]
@DmitrySoshnikov Nice. Thx.

**Comment by DmitrySoshnikov** [comment]
In addition, when a token doesn't define a class, but a single character, you can write it directly in BNF instead of defining first in lexical grammar. Writing `'.'` would work:

```
%left '.'
```

And in BENF:

```
Expr '.' Expr
```

The same with `'+'` and `'*'`.

Sometimes the actual token constants, like `NUMBER`, `PLUS`, etc make more sense.

**Comment by ckanner** [comment]
@DmitrySoshnikov 
And help me to see it
```
%lex

%%

\s+         /* skip whitespace */ return "";

\d+         return "NUMBER";

"[^"]*"     yytext = yytext.slice(1, -1); return "STRING";

g           return "g";
V           return "V";
HasLabel    return "HasLabel";

/lex

%left '.'

%{

/**
 * Recursive generic `Node` enum structure.
 */
#[derive(Debug)]
pub enum Step {

    V {
        id: &'static str,
    },

    HasLabel {
        label: &'static str,
    },

    Strategy {
        previous: Box<Step>,
        next: Box<Step>,
    },
}
/**
 * Final result type returned from `parse` method call.
 */
pub type TResult = Step;
/**
 * Hook executed on parse begin.
 */
fn on_parse_begin(_parser: &mut Parser, string: &'static str) {
    println!("Parsing: {:?}", string);
}

/**
 * Hook executed on parse end.
 */
fn on_parse_end(_parser: &mut Parser, result: &TResult) {
    println!("Parsed: {:?}", result);
}

%}

%%

Stmt
    : g '.' VStep '.' Step {
        |$3: Step; $5: Step| -> Step;

        $$ = Step::Strategy {
            previous: Box::new($3),
            next: Box::new($5),
        };
    };

Step
    : Step '.' Step {
        |$1: Step; $3: Step| -> Step;

        $$ = Step::Strategy {
            previous: Box::new($1),
            next: Box::new($3),
        };
    }

    | VStep {
        $$ = $1;
    }

    | HasLabelStep {
        $$ = $1;
    };

VStep
    : V ( STRING ) {
        |$3: &'static str| -> Step;

        $$ = Step::V {
            id: $3,
        };
    };

HasLabelStep
    : HasLabel ( STRING ) {
        |$3: &'static str| -> Step;

        $$ = Step::HasLabel {
            label: $3,
        };
    };


```
Then I generates it by `syntax-cli -g syntax/grammar.g -m LALR1 -o syntax/src/lib.rs`, and some errors occurs:
```
SyntaxError:

HasLabel    return "HasLabel";
                              ^
Unexpected token: "" at 11:30.
```

**Comment by DmitrySoshnikov** [comment]
@ckanner, the `STRING` needs escape for quotes:

```
\"[^\"]*\"     yytext = yytext.slice(1, -1); return "STRING";
```

**Comment by ckanner** [comment]
@DmitrySoshnikov 
I do this ok.
But the generated file of `lib.rs` has some error.
```
error: expected one of `async`, `const`, `crate`, `default`, `existential`, `extern`, `fn`, `pub`, `type`, `unsafe`, or `}`, found `;`
   --> syntax/src/lib.rs:789:6
    |
789 |     };
    |      ^ expected one of 11 possible tokens here

error: missing `fn`, `type`, or `const` for impl-item declaration
   --> syntax/src/lib.rs:789:7
    |
789 |       };
    |  _______^
790 | |
791 | | HasLabelStep
    | |_ missing `fn`, `type`, or `const`

error[E0599]: no method named `slice` found for type `&'static str` in the current scope
   --> syntax/src/lib.rs:538:27
    |
538 | self.yytext = self.yytext.slice(1, -1); return "STRING";
    |                           ^^^^^

error[E0308]: mismatched types
   --> syntax/src/lib.rs:779:31
    |
779 |   fn _handler5(&mut self) -> SV {
    |  _______________________________^
780 | | // Semantic values prologue.
781 | | self.values_stack.pop();
782 | | let mut _3 = pop!(self.values_stack, _2);
...   |
788 | |         };
789 | |     };
    | |_____^ expected enum `SV`, found ()
    |
    = note: expected type `SV`
               found type `()`

error: aborting due to 4 previous errors

Some errors occurred: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: Could not compile `syntax`.

To learn more, run the command again with --verbose.
```
And this is my grammar file:
```
%lex

%%

\s+           /* skip whitespace */ return "";

\d+           return "NUMBER";

\"[^\"]*\"    {  yytext = yytext.slice(1, -1); return "STRING"; }

"g"           return "g";
"V"           return "V";
"HasLabel"    return "HasLabel";

"("           return "(";
")"           return ")";
"."           return "DOT";

/lex

%left DOT

%{

/**
 * Recursive generic `Node` enum structure.
 */
#[derive(Debug)]
pub enum Step {

    V {
        id: &'static str,
    },

    HasLabel {
        label: &'static str,
    },

    Strategy {
        previous: Box<Step>,
        next: Box<Step>,
    },
}
/**
 * Final result type returned from `parse` method call.
 */
pub type TResult = Step;
/**
 * Hook executed on parse begin.
 */
fn on_parse_begin(_parser: &mut Parser, string: &'static str) {
    println!("Parsing: {:?}", string);
}

/**
 * Hook executed on parse end.
 */
fn on_parse_end(_parser: &mut Parser, result: &TResult) {
    println!("Parsed: {:?}", result);
}

%}

%%

Stmt
    : g DOT VStep DOT Step {
        |$3: Step; $5: Step| -> Step;

        $$ = Step::Strategy {
            previous: Box::new($3),
            next: Box::new($5),
        };
    };

Step
    : Step DOT Step {
        |$1: Step; $3: Step| -> Step;

        $$ = Step::Strategy {
            previous: Box::new($1),
            next: Box::new($3),
        };
    }

    | VStep {
        $$ = $1;
    }

    | HasLabelStep {
        $$ = $1;
    };

VStep
    : V ( STRING ) {
        |$3: &'static str| -> Step;

        $$ = Step::V {
            id: $3,
        };
    };

HasLabelStep
    : HasLabel ( STRING ) {
        |$3: &'static str| -> Step;

        $$ = Step::HasLabel {
            label: $3,
        };
    };
```
How can I fix it?

**Comment by ckanner** [comment]
The error fragment of the code:
```
fn _handler4(&mut self) -> SV {
// Semantic values prologue.
        let mut _1 = self.values_stack.pop().unwrap();

        let __ = _1;
        __
    }

    fn _handler5(&mut self) -> SV {
// Semantic values prologue.
        self.values_stack.pop();
        let mut _3 = pop!(self.values_stack, _2);
        self.values_stack.pop();
        self.values_stack.pop();

        let __ = Step::V {
            id: _3,
        };
    };

    HasLabelStep
    : HasLabel ( STRING ) {

    let __ = Step::HasLabel {
    label: _3,
    };
    SV::_1(__)
    }
```
It seems the generated code ```let __ = Step::V {
            id: _3,
        };
    };``` has illegal `;`. 
And ``` HasLabelStep
    : HasLabel ( STRING ) {

    let __ = Step::HasLabel {
    label: _3,
    };
    SV::_1(__)
    }``` is illegal.

**Comment by ckanner** [comment]
@DmitrySoshnikov 
This is the sample: https://github.com/ckanner/syntax-rust-sample
Can you help me find the reason of the error?

**Comment by DmitrySoshnikov** [comment]
@ckanner, it see `&'static str` is not supported yet, I'll open a separate issue for this.

```
|$3: &'static str| -> Step;
```

For now just define a type alias for it:

```
type Str = &'static str;
...
|$3: Str| -> Step;
```

**Comment by ckanner** [comment]
@DmitrySoshnikov I update it and generates it ok.
But it run `main` failed.
This is the sample: https://github.com/ckanner/syntax-rust-sample
error:
```
Parsing: "g.V(\"idx1\").V(\"idx2\")"
thread 'main' panicked at 'internal error: entered unreachable code', syntax/src/lib.rs:788:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:491
   5: core::sync::atomic::AtomicU64::store
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:425
   6: syntax::Parser::_handler5
             at syntax/src/lib.rs:788
   7: syntax::Tokenizer::_lex_rule8
             at syntax/src/lib.rs:682
   8: calc_parser::main
             at src/main.rs:13
   9: std::rt::lang_start::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  10: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  11: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:102
  12: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  13: std::rt::lang_start
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  14: calc_parser::main

Process finished with exit code 101
```

**Comment by DmitrySoshnikov** [comment]
In you `gremlin.g` you should be using `Token` type, not `Str`:

```
VStep
    : V '(' STRING ')' {
        |$3: Token| -> Step;

        $$ = Step::V {
            id: $3.value,
        };
    }
    ;

HasLabelStep
    : HASLABEL '(' STRING ')' {
        |$3: Token| -> Step;

        $$ = Step::HasLabel {
            label: $3.value,
        };
    }
    ;
```

The `$3.value` gives you actual string of a token.

**Comment by DmitrySoshnikov** [comment]
Closing this one, since '.' is a special symbol in BNF, and `DOT` token should be used. @ckanner, hopefully you were able to handle the Token type for the `STRING.`

**Comment by ckanner** [comment]
@DmitrySoshnikov It means the type of any matched token can be using `Token` type, whether it is `i32` or `Str`. Right?

**Comment by DmitrySoshnikov** [comment]
@ckanner, right, anything that is matched from the lexical grammar (like you `STRING`, `V`, etc) are of [Token](https://github.com/DmitrySoshnikov/syntax/blob/master/src/plugins/rust/templates/tokenizer.template.rs#L11-L21) type.

To access actual matched text, you use `value` property.

**Comment by ckanner** [comment]
@DmitrySoshnikov 
`g.V().out("label")`
`g.V().outE("label")`
This two statement, how can I defines the lex to reconize the `out` and `outE`.
This is the grammar:
```
%lex

%%

\s+           /* skip whitespace */ return "";

\d+           return "NUMBER";

\"[^"]*\"    {  let n = yytext.len(); yytext = &yytext[1..(n -1)]; return "STRING"; }

"V"           return "V";
"hasLabel"    return "HASLABEL";
"has"         return "HAS";
"eq"          return "EQ";
"lt"          return "LT";
"lte"         return "LTE";
"gt"          return "GT";
"gte"         return "GTE";
"inside"      return "INSIDE";
"between"     return "BETWEEN";
"out"         return "OUT";
"in"          return "IN";
"outE"        return "OUTE";
"inE"         return "INE";
"and"         return "AND";
"or"          return "OR";

/lex

%left '.'
%left ','

%{

/**
 * Recursive generic `Node` enum structure.
 */
#[derive(Debug)]
pub enum Value {
    Number(i32),
    Str(&'static str),
}

#[derive(Debug)]
pub enum Predicate {
    Eq(Value),
    Lt(i32),
    Lte(i32),
    Gt(i32),
    Gte(i32),
    Inside(i32, i32),
    Between(i32, i32),
}

#[derive(Debug)]
pub enum Step {

    V {
        id: Option<&'static str>,
    },

    HasLabel {
        label: &'static str,
    },

    Has {
        label: Option<&'static str>,
        key: &'static str,
        value: Value,
    },

    HasPredicate {
        label: Option<&'static str>,
        key: &'static str,
        predicate: Predicate,
    },

    Out {
        label: &'static str,
    },

    In {
        label: &'static str,
    },

    OutE {
        label: &'static str,
    },

    InE {
        label: &'static str,
    },

    And {
        step: Box<Step>,
    },

    Or {
        step: Box<Step>,
    },

    Strategy {
        previous: Box<Step>,
        next: Box<Step>,
    },
}
/**
 * Final result type returned from `parse` method call.
 */
pub type TResult = Step;
/**
 * Hook executed on parse begin.
 */
fn on_parse_begin(_parser: &mut Parser, string: &'static str) {
    println!("Parsing: {:?}", string);
}

/**
 * Hook executed on parse end.
 */
fn on_parse_end(_parser: &mut Parser, result: &TResult) {
    println!("Parsed: {:?}", result);
}

%}

%%

Stmt
    : 'g' '.' VStep '.' Step {
        |$3: Step; $5: Step| -> Step;

        $$ = Step::Strategy {
            previous: Box::new($3),
            next: Box::new($5),
        };
    }
    ;

Step
    : Step '.' Step {
        |$1: Step; $3: Step| -> Step;

        $$ = Step::Strategy {
            previous: Box::new($1),
            next: Box::new($3),
        };
    }

    | VStep {
        $$ = $1;
    }

    | HasLabelStep {
        $$ = $1;
    }

    | HasStep {
        $$ = $1;
    }

    | OutStep {
        $$ = $1;
    }

    | InStep {
        $$ = $1;
    }

    | AndStep {
        $$ = $1;
    }

    | OrStep {
        $$ = $1;
    }
    ;

VStep
    : V '(' STRING ')' {
        |$3: Token| -> Step;

        $$ = Step::V {
            id: Option::Some($3.value),
        };
    }

    | V '(' ')' {
        || -> Step;

        $$ = Step::V {
            id: Option::None,
        }
    }
    ;

HasLabelStep
    : HASLABEL '(' STRING ')' {
        |$3: Token| -> Step;

        $$ = Step::HasLabel {
            label: $3.value,
        };
    }
    ;

HasStep
    : HAS '(' STRING ',' STRING ',' STRING ')' {
        |$3: Token, $5: Token, $7: Token| -> Step;

        $$ = Step::Has {
            label: Option::Some($3.value),
            key: $5.value,
            value: Value::Str($7.value),
        }
    }

    | HAS '(' STRING ',' STRING ',' NUMBER ')' {
        |$3: Token, $5: Token, $7: Token| -> Step;

        $$ = Step::Has {
            label: Option::Some($3.value),
            key: $5.value,
            value: Value::Number($7.value.parse::<i32>().unwrap()),
        }
    }

    | HAS '(' STRING ',' STRING ')' {
        |$3: Token, $5: Token| -> Step;

        $$ = Step::Has {
            label: Option::None,
            key: $3.value,
            value: Value::Str($5.value),
        }
    }

    | HAS '(' STRING ',' NUMBER ')' {
        |$3: Token, $5: Token| -> Step;

        $$ = Step::Has {
            label: Option::None,
            key: $3.value,
            value: Value::Number($5.value.parse::<i32>().unwrap()),
        }
    }

    | HAS '(' STRING ',' STRING ','  Predicate ')' {
        |$3: Token, $5: Token, $7: Predicate| -> Step;

        $$ = Step::HasPredicate {
            label: Option::Some($3.value),
            key: $5.value,
            predicate: $7,
        }
    }

    | HAS '(' STRING ','  Predicate ')' {
        |$3: Token, $5: Predicate| -> Step;

        $$ = Step::HasPredicate {
            label: Option::None,
            key: $3.value,
            predicate: $5,
        }
    }
    ;

Predicate
    : EQ '(' STRING ')' {
        |$3: Token| -> Predicate;

        $$ = Predicate::Eq(Value::Str($3.value))
    }

    | EQ '(' NUMBER ')' {
        |$3: Token| -> Predicate;

        $$ = Predicate::Eq(Value::Number($3.value.parse::<i32>().unwrap()))
    }

    | LT '(' NUMBER ')' {
        |$3: Token| -> Predicate;

        $$ = Predicate::Lt($3.value.parse::<i32>().unwrap())
    }

    | LTE '(' NUMBER ')' {
        |$3: Token| -> Predicate;

        $$ = Predicate::Lte($3.value.parse::<i32>().unwrap())
    }

    | GT '(' NUMBER ')' {
        |$3: Token| -> Predicate;

        $$ = Predicate::Gt($3.value.parse::<i32>().unwrap())
    }

    | GTE '(' NUMBER ')' {
        |$3: Token| -> Predicate;

        $$ = Predicate::Gte($3.value.parse::<i32>().unwrap())
    }

    | INSIDE '(' NUMBER ',' NUMBER ')' {
        |$3: Token, $5: Token| -> Predicate;

        $$ = Predicate::Inside($3.value.parse::<i32>().unwrap(), $5.value.parse::<i32>().unwrap())
    }

    | BETWEEN '(' NUMBER ',' NUMBER ')' {
        |$3: Token, $5: Token| -> Predicate;

        $$ = Predicate::Between($3.value.parse::<i32>().unwrap(), $5.value.parse::<i32>().unwrap())
    }
    ;

OutStep
    : OUT '(' STRING ')' {
        |$3: Token| -> Step;

        $$ = Step::Out {
            label: $3.value,
        }
    }
    ;

InStep
    : IN '(' STRING ')' {
        |$3: Token| -> Step;

        $$ = Step::In {
            label: $3.value,
        }
    }
    ;

OutEStep
    : OUTE '(' STRING ')' {
        |$3: Token| -> Step;

        $$ = Step::OutE {
            label: $3.value,
        }
    }
    ;

InEStep
    : INE '(' STRING ')' {
        |$3: Token| -> Step;

        $$ = Step::InE {
            label: $3.value,
        }
    }
    ;

AndStep
    : AND '(' Traversal ')' {
        |$3: Step| -> Step;

        $$ = Step::And {
            step: Box::new($3),
        }
    }
    ;

OrStep
    : OR '(' Traversal ')' {
        |$3: Step| -> Step;

        $$ = Step::Or {
            step: Box::new($3),
        }
    }
    ;

Traversal
    : Traversal ',' Traversal {
        |$1: Step; $3: Step| -> Step;

        $$ = Step::Strategy {
            previous: Box::new($1),
            next: Box::new($3),
        };
    }

    | HasLabelStep {
        $$ = $1;
    }

    | HasStep {
        $$ = $1;
    }

    | OutEStep {
        $$ = $1;
    }

    | InEStep {
        $$ = $1;
    }
    ;

```

This is the error:
```
Parsing: "g.V().and(outE(\"knows\"), has(\"software\", \"lang\", eq(\"Java\")))"
thread 'main' panicked at '

g.V().and(outE("knows"), has("software", "lang", eq("Java")))
          ^
```

**Comment by DmitrySoshnikov** [comment]
@ckanner, tokenizer tries doing the longest match, so your `OUTE` token should be first:

```
'oute'     return 'OUTE'
'out'      return 'OUT'
```

alternatively you can use optional `e` at the end, and handle both generically:

```
oute?    { return yytext[yytext.length - 1] === 'e' ? 'OUTE' : 'OUT' }
```

Also, it's better to add boundary `\b`, so `out` is not matched in some `outfoo` text:

```
\boute\b    return 'OUTE'
\bout\b     return 'OUT'
```
